name: Simple docker-compose via ssh
author: AnvilFox
description: Docker prune/pull/compose via ssh
inputs:
  docker_host:
    description: docker user@host_ip
    required: true
  docker_port:
    description: ssh port
    default: '22'
    required: false
  ssh_pub:
    description: Remote SSH public
    required: true
  ssh_priv:
    description: Remote SSH private
    required: true
  compose_path:
    description: docker-compose.yml path on remote
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: terminal
  color: blue
