name: Simple docker-compose via ssh
author: AnvilFox
description: Docker prune/pull/compose via ssh
inputs:
  docker_host:
    description: Docker user@host_ip
    required: true
  bastion_host:
    description: Bastion user@host_ip
    required: true
  docker_port:
    description: SSH port
    default: '22'
    required: false
  ssh_pub:
    description: Github Agent SSH public
    required: true
  ssh_priv:
    description: Github Agent SSH private
    required: true
  compose_file_path:
    description: docker-compose.yml file path on remote
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: terminal
  color: blue
